### ISSUE TITLE
The types are incorrect

### ISSUE THREAD

**Issue by aminya** [terascope/fetch-github-release#142]
The types are incorrect when compared to the documentation. For example, `downloadRelease` returns a `Promise<string[]>`, and not `Promise<void>`

**Comment by aminya** [comment]
@peterdemartini This is not fixed yet. There are other errors. For example, `filterRelease?: () => boolean,` doesn't get any arguments as its inputs!

I just mentioned the return type as an example, but I meant that the types need a full review.

**Comment by peterdemartini** [comment]
This should now be [fixed](https://github.com/terascope/fetch-github-release/commit/9008f3b49988de57f863cee52ef8a5538c6d6391), in the future, we will happily accept pull requests to fix additional issues.

**Comment by peterdemartini** [comment]
@aminya please close this issue if you feel this is correctly resolved.

**Comment by aminya** [comment]
OK. Thanks!
