### ISSUE TITLE
Is it possible to use this to download assets from private repo?

### ISSUE THREAD

**Issue by lumenwrites** [terascope/fetch-github-release#265]
Hi! Thanks for making this awesome project, looks like it could save me a lot of time.

I have one question though - how difficult would it be to tweak this script to make it work with private repos?

**Comment by godber** [comment]
I'm not sure, I can't recall trying with a private repo, it looks like some parts of the code will use a `GITHUB_TOKEN` environment variable:

https://github.com/terascope/fetch-github-release/blob/d48ecc651b49178fcc2b73e28dd26dee70336f25/src/getReleases.ts

**Comment by lumenwrites** [comment]
@godber Thank you very much! Simply setting the `GITHUB_TOKEN` variable before running script made it work like magic, it just downloaded the files from my private repo!
