### ISSUE TITLE
File corruption

### ISSUE THREAD

**Issue by andrewjanssen** [terascope/fetch-github-release#283]
The process may exit before the `WriteStream` finishes writing to the target file, resulting in a corrupted file.

Fix is in PR [#281](https://github.com/terascope/fetch-github-release/pull/281).

**Comment by godber** [comment]
@busma13 after completing https://github.com/terascope/fetch-github-release/issues/282 you can review the PR above.

**Comment by godber** [comment]
@andrewjanssen if you don't mind following up here and confirming that the new build (containing your fix) resolves the problem you were experiencing.  I'm going to leave the issue open for your feedback.  If you don't have time I'll just close this eventually, assuming it's really fixed.

**Comment by godber** [comment]
Ok, that should be fixed in https://www.npmjs.com/package/@terascope/fetch-github-release/v/0.8.10


Thanks again for the contribution and have a great day!

**Comment by andrewjanssen** [comment]
> @andrewjanssen if you don't mind confirming that the new build (containing your fix) resolves the problem

Sure thing, give me a day or two.

**Comment by andrewjanssen** [comment]
> @andrewjanssen if you don't mind confirming that the new build (containing your fix) resolves the problem

Confirmed: `0.8.9` always exhibits the bug for me, and `0.8.10` never exhibits the bug. Case closed! Thanks!
