### ISSUE TITLE
Backoff and retry if github ratelimit exceeded

### ISSUE THREAD

**Issue by busma13** [terascope/fetch-github-release#300]
It looks like the `got` request to github can hit a secondary rate limit in CI for too many concurrent requests. We should add an automatic retry if the response code is a 403.

github rate limit docs:
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

failed test:
https://github.com/terascope/teraslice/actions/runs/10097840850/job/27923672785

**Comment by busma13** [comment]
We decided it was best to handle this issue from within the application using this library.

**Comment by godber** [comment]
> We decided it was best to handle this issue from within the application using this library.

Why?  I would think all users of `fetch-github-release` would benefit from this change and is no way specific to our use case.
