### ISSUE TITLE
401 auth errors

### ISSUE THREAD

**Issue by godber** [terascope/fetch-github-release#88]
This week, teraslice-cli asset downloads started failing with 401 errors unless the user specifies a `GITHUB_TOKEN` environment variable.  I think it's because the github API has started handling empty tokens differently:

https://github.com/terascope/fetch-github-release/blob/master/src/getReleases.js#L12

A temporary work around is to just set your GITHUB_TOKEN environment variable.

**Comment by peterdemartini** [comment]
I think this has been fixed
